{% set version = "2.16.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-r.devices
  version: {{ version|replace("-", "_") }}

source:
  fn: R.devices_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/R.devices_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/R.devices/R.devices_{{ version }}.tar.gz
  sha256: adedb928e6e6d1951d512f13688aa8ad4558a8fbc5b3e58cc0901ff106b6f497

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: digest (>= 0.6.13), Cairo (>= 1.5-9), R.rsp
requirements:
  host:
    - r-base
    - r-r.methodss3 >=1.7.1
    - r-r.oo >=1.21.0
    - r-r.utils >=2.6.0
    - r-base64enc >=0.1_2

  run:
    - r-base
    - r-r.methodss3 >=1.7.1
    - r-r.oo >=1.21.0
    - r-r.utils >=2.6.0
    - r-base64enc >=0.1_2

test:
  commands:
    - $R -e "library('R.devices')"           # [not win]
    - "\"%R%\" -e \"library('R.devices')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/R.devices
  license: LGPL (>= 2.1)
  summary: Functions for creating plots and image files in a unified way regardless of output
    format (EPS, PDF, PNG, SVG, TIFF, WMF, etc.). Default device options as well as
    scales and aspect ratios are controlled in a uniform way across all device types.
    Switching output format requires minimal changes in code. This package is ideal
    for large-scale batch processing, because it will never leave open graphics devices
    or incomplete image files behind, even on errors or user interrupts.
  license_family: LGPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
