appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: NeVSg++lqcGgxxero8pKLkotmpsBsP/KEoaekmX3wGEkUNqXl9t1Q4RchRCDQefazNsGtLIpi5CGCvrOWJ4RF+QhKeqeRDR1R+tvgCVQr07NSAMGw2xdFekOJkf+zAv3vfL6JpqMHX4K7KQ8DzlEyDcq27m5l8enF8KkLFeS9dA6en8Xz4q8/f85ttpPY4gWUw6+lZ9VGU5IJOHmz4CdqnstVb7tMOcP6JOhjI6UHW+KmMKiis2BNZaFs3kYQxarDLPQuDMRhsWcUCSIg1jCjFCdTSa5Z7V/+EiNqzHum3uCAAoGu5jY1T+rOVLRsqymt2ALsXt9MuZ7CX7Ms3oE0ml3xmq7l1kiiyv97/f/aPlzd9w/QICRt0wFGR3uR1TltqPLD6mIgTn/EaUKm5/BWgUHkRbjDSVI0ml0hA2vhKqlqcZpdcaIMP1utmSN8MQoB8jAx9FSkV5GX0qfVUR+Csjy+5TqkLbcikpsbGe4C+0g6wzDT579T158EhqK5fhXe8PQbzmv4rwRd2WgkUvdhxEWA9KJ51R2+9eGTwF1LHOZEXHfuY0yBFsyBXDG6I5mnNHDlNMR+6f2K7tD3bTJo9KBmO/YQUU5AVpiXHtpP6UfB05lDUX4ZnV51LsSnes54mfew8pw5xSkhlXNjBTx79EJx6YVn0mpA4tutGLXnmA=}
